-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 23:18:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelo_ventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelo_ventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo_ventas` DEFAULT CHARACTER SET utf8 ;
USE `modelo_ventas` ;

-- -----------------------------------------------------
-- Table `modelo_ventas`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_ventas`.`proveedor` (
  `id_proveedor` INT NOT NULL,
  `ruc_proveedor` VARCHAR(15) NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `telefono_proveedor` VARCHAR(15) NOT NULL,
  `direccion_proveedor` VARCHAR(45) NOT NULL,
  `estado_proveedor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_ventas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_ventas`.`categoria` (
  `id_categoria` INT NOT NULL,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  `estado_categoria` VARCHAR(10) NOT NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_categoria_proveedor1_idx` (`proveedor_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `modelo_ventas`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_ventas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_ventas`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(100) NOT NULL,
  `telefono_cliente` VARCHAR(15) NOT NULL,
  `direccion_cliente` VARCHAR(45) NOT NULL,
  `estado_cliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_ventas`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_ventas`.`producto` (
  `id_producto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `estado_producto` VARCHAR(10) NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  `proveedor_id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_categoria_idx` (`categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_producto_proveedor1_idx` (`proveedor_id_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `modelo_ventas`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_id_proveedor`)
    REFERENCES `modelo_ventas`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_ventas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_ventas`.`usuario` (
  `id_usuario` INT NOT NULL,
  `usuario` VARCHAR(10) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasena_usuario` VARCHAR(45) NOT NULL,
  `rol_usuario` VARCHAR(20) NOT NULL,
  `caja_usuario` VARCHAR(15) NOT NULL,
  `estado_usuario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_ventas`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_ventas`.`detalle_ventas` (
  `idDetalleVentas` INT NOT NULL AUTO_INCREMENT,
  `producto_id_producto` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`idDetalleVentas`),
  INDEX `fk_ventas_producto1_idx` (`producto_id_producto` ASC) VISIBLE,
  INDEX `fk_ventas_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_producto1`
    FOREIGN KEY (`producto_id_producto`)
    REFERENCES `modelo_ventas`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `modelo_ventas`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
